(function() {
  window.CL_OUTPUTS = {
    init: function(supabase) {
      var panel = document.getElementById("cl-tab-outputs");
      if (!panel) return;
      panel.innerHTML = "<div class=\"ptab-content\" id=\"tab-outputs\">\n\n    <div class=\"info-box\">\n      <strong>🤖 AI Tool Outputs:</strong> Every document, post, and file generated by your AI tools lives here. Select a tool on the left to view its outputs. Published marketing content is shown at the bottom.\n    </div>\n\n    <div class=\"tool-outputs-layout\">\n\n      <!-- Left: Tool tiles -->\n      <div>\n        <div class=\"card-title\" style=\"margin-bottom:12px; font-size:13px; color:var(--text-muted); font-weight:600; text-transform:uppercase; letter-spacing:0.5px;\">YOUR TOOLS</div>\n        <div class=\"tool-tiles\" id=\"tool-tiles-list\"></div>\n      </div>\n\n      <!-- Right: Output panel -->\n      <div class=\"tool-output-panel\" id=\"tool-output-panel\">\n        <div class=\"tool-output-header\">\n          <div class=\"tool-output-title\" id=\"output-panel-title\">Select a tool to view outputs</div>\n        </div>\n        <div class=\"tool-output-body\" id=\"output-panel-body\">\n          <div class=\"empty-state\" style=\"padding:40px 20px;\">\n            <div class=\"empty-state-icon\">👈</div>\n            <h3>Choose a tool</h3>\n            <p>Select any tool from the left to view its generated outputs</p>\n          </div>\n        </div>\n      </div>\n\n    </div>\n\n    <!-- Published section -->\n    <div class=\"published-section\">\n      <div class=\"published-section-title\">\n        ✅ Published — Marketing Outputs History\n      </div>\n      <div id=\"published-grid\" class=\"published-grid\"></div>\n      <div class=\"empty-state\" id=\"published-empty\" style=\"display:none; padding:32px 20px;\">\n        <div class=\"empty-state-icon\" style=\"font-size:36px;\">📭</div>\n        <p>Nothing published yet — approved posts will appear here after posting</p>\n      </div>\n    </div>\n\n  </div>";
      loadToolTiles();
    }
  };

  // AI Outputs functions
  async function loadToolTiles() {
  const profile = await getUserProfile();
  const activeIds = profile?.activated_tools || ['chatbot'];

  const tilesEl = document.getElementById('tool-tiles-list');
  tilesEl.innerHTML = ALL_TOOLS.map(tool => {
    const isActive = activeIds.includes(tool.id);
    return `
      <div class="tool-tile ${isActive ? '' : 'inactive'} ${currentToolId === tool.id ? 'active' : ''}"
           onclick="selectTool('${tool.id}', ${isActive})">
        <span class="tool-tile-icon">${tool.icon}</span>
        <div class="tool-tile-info">
          <div class="tool-tile-name">${tool.name}</div>
          <div class="tool-tile-count" id="tile-count-${tool.id}">${isActive ? 'Loading...' : 'Not activated'}</div>
        </div>
        ${!isActive ? '<span class="tool-tile-lock">🔒</span>' : ''}
      </div>
    `;
  }).join('');

  // Load output counts for active tools
  const { data: { user } } = await supabaseClient.auth.getUser();
  for (const tool of ALL_TOOLS.filter(t => activeIds.includes(t.id))) {
    const { count } = await supabaseClient
      .from('content_library')
      .select('*', { count: 'exact', head: true })
      .eq('user_id', user.id)
      .eq('tool_source', tool.id);
    const el = document.getElementById(`tile-count-${tool.id}`);
    if (el) el.textContent = count ? `${count} output${count !== 1 ? 's' : ''}` : 'No outputs yet';
  }
}

window.selectTool = async function(toolId, isActive) {
  currentToolId = toolId;
  const tool = ALL_TOOLS.find(t => t.id === toolId);
  if (!tool) return;

  // Update active tile
  document.querySelectorAll('.tool-tile').forEach(t => t.classList.remove('active'));
  event.currentTarget.classList.add('active');

  const panel = document.getElementById('tool-output-panel');
  const titleEl = document.getElementById('output-panel-title');
  const bodyEl = document.getElementById('output-panel-body');

  titleEl.textContent = `${tool.icon} ${tool.name}`;

  if (!isActive) {
    // Show upsell panel
    bodyEl.innerHTML = `
      <div class="upsell-panel">
        <div class="upsell-icon">${tool.icon}</div>
        <div class="upsell-title">${tool.name}</div>
        <div class="upsell-desc">Activate this tool to start generating AI-powered outputs. Everything this tool creates will appear here for easy access.</div>
        <div class="upsell-price">$${tool.price}/month</div>
        <div class="upsell-features" id="upsell-features-${tool.id}">
          <div class="upsell-feature">⏱ Set up in minutes — no tech knowledge needed</div>
          <div class="upsell-feature">🤖 AI does the heavy lifting for you</div>
          <div class="upsell-feature">📁 All outputs saved here automatically</div>
          <div class="upsell-feature">❌ Cancel anytime</div>
        </div>
        <a href="/dashboard.html?activate=${tool.id}" class="btn btn-orange" style="font-size:15px; padding:14px 32px;">
          🚀 Activate ${tool.name}
        </a>
      </div>
    `;
    return;
  }

  // Load active tool outputs
  bodyEl.innerHTML = '<div class="loading show"><div class="spinner"></div><p>Loading outputs...</p></div>';

  const { data: { user } } = await supabaseClient.auth.getUser();
  const { data: outputs } = await supabaseClient
    .from('content_library')
    .select('*')
    .eq('user_id', user.id)
    .eq('tool_source', toolId)
    .order('created_at', { ascending: false });

  if (!outputs?.length) {
    bodyEl.innerHTML = `
      <div class="empty-state" style="padding:40px 20px;">
        <div class="empty-state-icon">${tool.icon}</div>
        <h3>No outputs yet</h3>
        <p>Open the tool and start generating content — everything will appear here automatically.</p>
        <a href="${tool.link}" class="btn btn-primary" style="margin-top:16px;">Open ${tool.name} →</a>
      </div>
    `;
    return;
  }

  bodyEl.innerHTML = `
    <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:16px;">
      <span style="font-size:13px; color:var(--text-muted);">${outputs.length} output${outputs.length!==1?'s':''}</span>
      <a href="${tool.link}" class="btn btn-outline btn-sm">Open Tool →</a>
    </div>
    <div class="output-list">
      ${outputs.map(item => `
        <div class="output-item">
          <span class="output-item-icon">${item.image_url ? '🖼️' : getDocIcon(item.content_type)}</span>
          <div class="output-item-info">
            <div class="output-item-name">${escHtml(item.title||'Untitled')}</div>
            <div class="output-item-meta">${item.content_type||''} &nbsp;•&nbsp; ${new Date(item.created_at).toLocaleDateString('en-AU')}</div>
          </div>
          <div class="output-item-actions">
            ${item.image_url ? `<button class="btn btn-outline btn-sm" onclick="window.open('${item.image_url}','_blank')">👁 View</button>` : ''}
          </div>
        </div>
      `).join('')}
    </div>
  `;
};

// Published history
async function loadPublished() {
  const { data: { user } } = await supabaseClient.auth.getUser();
  const { data } = await supabaseClient
    .from('publishing_queue')
    .select('*')
    .eq('user_id', user.id)
    .eq('status', 'posted')
    .order('posted_at', { ascending: false })
    .limit(20);

  const grid = document.getElementById('published-grid');
  const empty = document.getElementById('published-empty');

  if (!data?.length) {
    grid.innerHTML = '';
    empty.style.display = 'block';
    return;
  }

  empty.style.display = 'none';
  const platformIcons = { facebook: '📘', instagram: '📸', linkedin: '💼' };

  grid.innerHTML = data.map(item => {
    const platforms = Array.isArray(item.platform) ? item.platform : (item.platform||'').split(',').filter(Boolean);
    return `
      <div class="published-card">
        <div class="published-card-img">
          ${item.graphic_url ? `<img src="${item.graphic_url}" onerror="this.parentNode.textContent='📣'">` : '📣'}
        </div>
        <div class="published-card-info">
          <div class="published-card-date">📅 ${item.posted_at ? new Date(item.posted_at).toLocaleDateString('en-AU') : 'Unknown date'}</div>
          <div class="published-card-platforms">${platforms.map(p=>`<span class="platform-chip">${platformIcons[p]||''} ${p}</span>`).join('')}</div>
        </div>
      </div>
    `;
  }).join('');
}

// ─── MODALS ────────────────────────────────────
window.closeModal = function(id) {
  document.getElementById(id).classList.remove('show');
};

// ─── UTILS ─────────────────────────────────────

})();